### ISSUE TITLE
mat2nc.py

### ISSUE THREAD

**Issue by hoseinsalehi** [mcuntz/jams_python#7]
Hi
I want to convert .mat file to .nc file with your scripts, but I get an error:
Traceback (most recent call last):
  File "mat2nc.py", line 11, in <module>
    from jams.writenetcdf import writenetcdf
ModuleNotFoundError: No module named 'jams.writenetcdf'

How can I solve this error?
Thanks

**Comment by julemai** [comment]
Hi,

could you just try to replace line 11 with `from writenetcdf import writenetcdf`.

Cheers,
Julie

**Comment by hoseinsalehi** [comment]
Thanks @julemai for quick reply.
After this we should change line 12 with: from readnetcdf  import readnetcdf
And in writenetcdf.py line 5 with: from readnetcdf import readnetcdf

My new problem is where should I define my .mat file in these scripts?

**Comment by julemai** [comment]
Hey,

you won't make any changes in the script itself to define the Matlab file. Just start a new Python script and `import mat2nc from mat2nc` and call, for example
```
mat2nc('test.mat')
```

Examples are given in the description of the script. Hope that helps.

**Comment by hoseinsalehi** [comment]
Thank you very much @julemai for your help.
 It was very useful

**Comment by julemai** [comment]
Awesome! I just committed the fix of removing the reference to `jams`. Thanks for spotting and reporting this. :)

Good luck with the script. It assumes pretty simple Matlab files. I hope it works for you.
