### ISSUE TITLE
writenetcdf.py Fill Value

### ISSUE THREAD

**Issue by konhee93** [mcuntz/jams_python#8]
Hello,

I have a script converting grib2 files into netcdf, and writenetcdf.py is giving me errors. 
My guess is there were some changes made to the netcdf4 module...

Error occured in line 212 for me

` File "/home/konhee/miniconda3/lib/python3.7/site-packages/jams-5.0.0-py3.7.egg/jams/writenetcdf.py", line 212, in writenetcdf
    hand.setncattr(k, attributes[k])
  File "netCDF4/_netCDF4.pyx", line 4167, in netCDF4._netCDF4.Variable.setncattr
AttributeError: _FillValue attribute must be set when variable is created (using fill_value keyword to createVariable)`

Would be great if this can be looked at.

Thanks!

**Comment by mcuntz** [comment]
Dear drg2314,

thanks for finding this bug. We did not catch it because people who use this routine seem to use also missing_value instead of _FillValue. So all tests were run with missing_value and none with _FillValue.

I have committed the fix. Works for me now.

Regards
Matthias

**Comment by julemai** [comment]
Hi Matthias,

it must be due to a recent update in Python. I just found this in one of my other scripts too just today. The script was working perfectly fine just before I setup my Mac new a couple weeks ago.

Viele Grüße
Jule

**Comment by konhee93** [comment]
Thanks for the quick fix Matthias,

It's working for me.
Looks like this was due to a change made in netcdf4-python a year ago.

https://github.com/Unidata/netcdf4-python/issues/959

Thanks!

**Comment by konhee93** [comment]
Hey @julemai  (This is Konhee),

FYI, on top of the changes to this code, I had to make another change to the grib to netcdf tool you've provided.
datetime package was no longer available with netcdf, so I had to import cftime as a workaround on the date2dec.py file.

After the datetime and fill_value (which Matthias has addressed), it seems the script runs well!

**Comment by julemai** [comment]
Hey Konhee,

That’s great! Thanks for letting me know. I also just started adjusting my scripts since I just got my new python setup. Thanks for giving me already a heads up.

Hope you’re doing well!

Cheers,
Julie

**Comment by mcuntz** [comment]
Hey Konhee,

what did you have to change in date2dec? There is quite an elaborate import in date2dec because the time routines were an own package in the past, were part of netcdf4 and became its own package again (with a different name):
    try:
        import cftime as nt
    except:
        import netCDF4 as nt
    try:
        tst = nt.date2num
        tst = nt.datetime
    except:
        try:
            import netcdftime as nt
            if ((nt.__version__ <= '0.9.2') & (calendar == '360_day')):
                raise ValueError("date2dec error: Your version of netcdftime.py is equal"
                                 " or below 0.9.2. The 360_day calendar does not work with"
                                 " arrays here. Please download a newer one.")
        except:
            raise ImportError('Could not determine netcdf time library.')

So you see, we are catering for quite some versions. Did this not work for you? What did you have to change?

Regards
Matthias

**Comment by konhee93** [comment]
@mcuntz 

It looks like I was working of off an older version of the package (provided by Julie before I knew about this github).
The current date2dec.py seems to have taken care of the issue I was having.

Thanks!

**Comment by mcuntz** [comment]
O.K., then I close this issue.

Cheers
Matthias
